# Generated by Django 5.1.5 on 2025-01-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
    ]
